apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
      - name: evaluation-service
        image: rayenmekni123/evaluation-service:latest
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-evaluation-service:3306/evaluation
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-evaluation-secret
              key: root-password
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
spec:
  type: NodePort
  selector:
    app: evaluation-service
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30090
